# Generated by Django 4.1.1 on 2022-09-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=0)),
                ('valoracion', models.PositiveSmallIntegerField(blank=True)),
                ('comentario', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultura.ciudades')),
            ],
        ),
    ]
