# Generated by Django 4.1.1 on 2022-10-04 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0002_alter_actividades_id_alter_actividades_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='nombre_actividad',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
